#!/bin/bash

set -ex

POSTFIX="$(date +%s)-$(head -c 20 /dev/random  | sha1sum | awk '{print $1;}')"

cat <<EOF | nomad job run -
job "example-${POSTFIX}" {
  datacenters = ["default"]

  type = "batch"
  group "group-${POSTFIX}" {
    count = 1

    task "task-${POSTFIX}" {
      driver = "raw_exec"

      config {
	command = "/bin/bash"
	args = ["-c", "(date; echo I am ${POSTFIX}; sleep 6) >> /tmp/jobs"]
      }


      resources {
        cpu    = 20
        memory = 10
      }
    }
  }
}
EOF

